### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by yongloon** [DOkwufulueze/eth-vue#16]
Hello, I faced this error when entering "truffle compile" in the terminal.

![screen shot 2018-09-01 at 11 29 36 pm](https://user-images.githubusercontent.com/12860854/44947378-fd8ece00-ae3e-11e8-81e0-136da355fd5e.png)

**Comment by DOkwufulueze** [comment]
Hi, @nyl9488 
Apologies for the late reply.

While we'll handle all promise rejections in the next update, I'll like to point out that issues folks face when compiling `eth-vue` are due to Solidity versions incompatibility. We were supposed to have upgraded the `eth-vue` version some weeks ago, but we've been unable to so far due to some very pressing reasons.
Please bear with us. We'll upgrade and report back to you and other Devs that have faced this same issue.

But for now you can use Solidity `v0.4.18` to compile your dApp and you should have no problem.

**Comment by DOkwufulueze** [comment]
Hey, @nyl9488 

`eth-vue` upgrades have begun and things seem good now.
There's a conversation going on [here](https://github.com/DOkwufulueze/eth-vue/issues/18) about this. [Here's](https://github.com/DOkwufulueze/eth-vue/issues/18#issuecomment-464407734) one of my comments.

**Comment by DOkwufulueze** [comment]
Closing as this issue resolved in recent updates.
