### ISSUE TITLE
Too much errors while compiling

### ISSUE THREAD

**Issue by TranDinhKhang** [DOkwufulueze/eth-vue#17]
Hi guys,

I cannot compile the smart contracts due to the errors. Anyone has solutions pls :(
![image](https://user-images.githubusercontent.com/17232235/52693641-d580ca80-2f99-11e9-81dd-1a80f23ea43b.png)

**Comment by DOkwufulueze** [comment]
Hey, @TranDinhKhang 
Sorry about the errors in compilation. But this issue is related to [this](https://github.com/DOkwufulueze/eth-vue/issues/13) and our response is [here](https://github.com/DOkwufulueze/eth-vue/issues/13#issuecomment-406952152).

Again, this is due to the Solidity version `eth-vue` runs on.
We hoped to upgrade the version but we've not had the time yet. We'll consider doing this sooner and get back to you once done.

While we plan on upgrading, you can run this truffle box on `Solidity v0.4.18` or raise a PR with the upgraded version and we'll merge.

Please bear with us.

**Comment by DOkwufulueze** [comment]
@TranDinhKhang 

Upgrade has begun and things seem good now.
There's a conversation going on [here](https://github.com/DOkwufulueze/eth-vue/issues/18) about this. [Here's](https://github.com/DOkwufulueze/eth-vue/issues/18#issuecomment-464407734) one of my comments.

**Comment by DOkwufulueze** [comment]
Closing as this is resolved.
